services:
  blogspot-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/server/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    

  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"

  blogspot-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/frontend/src

    ports:
      - "5173:5173"
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pdb

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/pdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - 9090:8080
    command:
      - start-dev

volumes:
  data-volume:
  postgres_data:

